# Generated by Django 4.2.3 on 2024-03-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HorizonHues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(default=None, max_length=100, null=True)),
                ('description', models.CharField(default=None, max_length=1000, null=True)),
                ('image', models.CharField(default=None, max_length=2000, null=True)),
                ('prev_price_couple', models.IntegerField(default=None, max_length=10, null=True)),
                ('prev_price_family', models.IntegerField(default=None, max_length=10, null=True)),
                ('prev_price_friends', models.IntegerField(default=None, max_length=10, null=True)),
                ('discount', models.IntegerField(default=None, max_length=10, null=True)),
                ('discounted_price', models.IntegerField(default=None, max_length=10, null=True)),
            ],
        ),
    ]
