# Generated by Django 4.2.3 on 2024-03-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HorizonHues', '0002_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='discount',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='discounted_price',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='prev_price_couple',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='prev_price_family',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='prev_price_friends',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
