# Generated by Django 4.2.3 on 2024-03-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HorizonHues', '0004_rename_prev_price_couple_package_prev_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='discounted_price',
        ),
    ]
