# Generated by Django 4.2.3 on 2024-03-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HorizonHues', '0005_remove_package_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='discounted_price',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
