# Generated by Django 4.2.3 on 2024-03-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HorizonHues', '0006_package_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='discounted_price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
