# Generated by Django 4.2.3 on 2024-03-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HorizonHues', '0007_alter_package_discounted_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy_now',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.IntegerField(default=None, null=True)),
                ('location', models.CharField(default=None, max_length=100, null=True)),
                ('image1', models.CharField(default=None, max_length=2000, null=True)),
                ('image2', models.CharField(default=None, max_length=2000, null=True)),
                ('image3', models.CharField(default=None, max_length=2000, null=True)),
                ('image4', models.CharField(default=None, max_length=2000, null=True)),
                ('activity1', models.CharField(default=None, max_length=1000, null=True)),
                ('activity2', models.CharField(default=None, max_length=1000, null=True)),
                ('activity3', models.CharField(default=None, max_length=1000, null=True)),
                ('activity4', models.CharField(default=None, max_length=1000, null=True)),
                ('activity5', models.CharField(default=None, max_length=5000, null=True)),
                ('itenary1', models.CharField(default=None, max_length=5000, null=True)),
                ('itenary2', models.CharField(default=None, max_length=5000, null=True)),
                ('itenary3', models.CharField(default=None, max_length=5000, null=True)),
                ('itenary4', models.CharField(default=None, max_length=5000, null=True)),
            ],
        ),
    ]
