# Generated by Django 5.0.2 on 2024-03-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HorizonHues", "0008_buy_now"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("package_id", models.AutoField(primary_key=True, serialize=False)),
                ("location", models.CharField(default=None, max_length=100, null=True)),
                (
                    "description",
                    models.CharField(default=None, max_length=1000, null=True),
                ),
                ("image", models.CharField(default=None, max_length=2000, null=True)),
                ("group", models.CharField(default=None, max_length=1000, null=True)),
                ("prev_price", models.IntegerField(default=None, null=True)),
                ("discount", models.IntegerField(default=None, null=True)),
                (
                    "discounted_price",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
            ],
        ),
    ]
