# Generated by Django 4.2.3 on 2024-03-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HorizonHues', '0010_mycart_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('sno', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('review', models.TextField()),
                ('suggestion', models.TextField()),
            ],
        ),
    ]
