# Generated by Django 4.2.3 on 2024-03-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HorizonHues', '0011_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='days',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='nights',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
