# Generated by Django 4.2.3 on 2024-03-22 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HorizonHues', '0013_mycart_days_mycart_nights'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('fname', models.CharField(default=None, max_length=30, null=True)),
                ('lname', models.CharField(default=None, max_length=30, null=True)),
                ('email', models.CharField(default=None, max_length=50, null=True)),
                ('phone', models.CharField(default=None, max_length=100, null=True)),
                ('package_id', models.IntegerField(default=None, null=True)),
                ('location', models.CharField(default=None, max_length=100, null=True)),
                ('prev_price', models.IntegerField(default=None, null=True)),
                ('discount', models.IntegerField(default=None, null=True)),
                ('discounted_price', models.IntegerField(blank=True, default=None, null=True)),
                ('nights', models.IntegerField(default=None, null=True)),
                ('days', models.IntegerField(default=None, null=True)),
                ('checkin_date', models.CharField(default=None, max_length=30, null=True)),
                ('checkout_date', models.CharField(default=None, max_length=30, null=True)),
            ],
        ),
    ]
