# Generated by Django 4.2.3 on 2024-03-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HorizonHues', '0014_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
