# Generated by Django 4.2.3 on 2024-03-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HorizonHues', '0016_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_now',
            name='itenary_image2',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='buy_now',
            name='itenary_image3',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='buy_now',
            name='itenary_image4',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='buy_now',
            name='iterary_image1',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
    ]
