# Generated by Django 4.2.3 on 2024-03-23 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HorizonHues', '0017_buy_now_itenary_image2_buy_now_itenary_image3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy_now',
            old_name='iterary_image1',
            new_name='itenary_image1',
        ),
    ]
