# Generated by Django 4.2.3 on 2024-03-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HorizonHues', '0020_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('Hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(default=None, max_length=100, null=True)),
                ('description', models.CharField(default=None, max_length=1000, null=True)),
                ('image', models.CharField(default=None, max_length=2000, null=True)),
                ('group', models.CharField(default=None, max_length=1000, null=True)),
                ('prev_price', models.IntegerField(default=None, null=True)),
                ('discount', models.IntegerField(default=None, null=True)),
                ('discounted_price', models.IntegerField(blank=True, default=None, null=True)),
                ('nights', models.IntegerField(default=None, null=True)),
                ('days', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
