# Generated by Django 4.2.3 on 2024-03-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HorizonHues', '0021_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='days',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='nights',
        ),
    ]
